"""Builds the exact Claude prompt used by stock-dashboard/src/app/api/ai-analysis/route.ts.
Keep the data-section formatting byte-for-byte in sync with the TS template —
the frontend/prompt viewer and any future model comparisons depend on it
matching. `prompt_news.py` reuses `_build_data_sections` to build a second,
web-search-aware variant on top of the same underlying data.
"""
from __future__ import annotations

from typing import List

from . import analytics as A


def _sign(v: float) -> str:
    return "+" if v >= 0 else ""


def _build_data_sections(all_data: A.AllData, today: str) -> str:
    """Everything the model needs to see before the response-format
    instructions: portfolio summary, signal changes, performance, snapshot
    table, forward-return effectiveness. Shared by every prompt variant."""
    tickers = list(all_data.keys())
    consensus = A.market_consensus(all_data)
    fwd = A.aggregate_forward_returns(all_data)
    snapshot = A.latest_snapshot(all_data)

    signal_changes: List[str] = []
    for r in snapshot:
        rows = all_data[r.ticker]
        if len(rows) >= 2:
            last, prev = rows[-1], rows[-2]
            if last.signal != prev.signal:
                signal_changes.append(f"{r.ticker}: {prev.signal}→{last.signal}")

    port_sim = A.portfolio_simulation(all_data)
    port_last = port_sim[-1] if port_sim else None
    if port_last:
        port_line = (
            f"Strategy {_sign(port_last.strategy)}{port_last.strategy:.1f}% vs "
            f"buy-and-hold {_sign(port_last.bah)}{port_last.bah:.1f}% (equal-weight across all tickers)"
        )
    else:
        port_line = "Portfolio simulation unavailable"

    snapshot_lines: List[str] = []
    for r in snapshot:
        rows = all_data[r.ticker]
        last = rows[-1]
        stats = A.trade_stats(rows)
        perf = (
            f"wr={round(stats.win_rate)}% exp={_sign(stats.expectancy)}{stats.expectancy:.1f}%"
            if stats.total_trades
            else "no_completed_trades"
        )
        snapshot_lines.append(" | ".join([
            r.ticker.ljust(5),
            r.signal.ljust(4),
            "$" + f"{r.price:.2f}".rjust(8),
            f"streak={r.streak['signal']}×{r.streak['days']}d".ljust(14),
            f"period={_sign(r.period_change_pct)}{r.period_change_pct:.1f}%".ljust(14),
            "conf=" + f"{last.confidence:.0f}".rjust(3),
            "adx=" + f"{last.adx:.0f}".rjust(3),
            perf,
        ]))
    snapshot_block = "\n".join(snapshot_lines)

    fwd_line = (
        f"BUY: {_sign(fwd['BUY']['avg'])}{fwd['BUY']['avg']:.3f}% (n={fwd['BUY']['count']}) | "
        f"SELL: {_sign(fwd['SELL']['avg'])}{fwd['SELL']['avg']:.3f}% (n={fwd['SELL']['count']}) | "
        f"HOLD: {_sign(fwd['HOLD']['avg'])}{fwd['HOLD']['avg']:.3f}% (n={fwd['HOLD']['count']})"
    )

    signal_changes_line = (
        f"Signal changes since yesterday: {', '.join(signal_changes)}"
        if signal_changes
        else "No signal changes since yesterday."
    )

    return f"""You are reviewing algorithmic stock signals generated by a systematic trading bot. Today is {today}.

Portfolio: {len(tickers)} tickers | BUY: {consensus['BUY']} | SELL: {consensus['SELL']} | HOLD: {consensus['HOLD']}
{signal_changes_line}

Portfolio performance (equal-weight simulation):
{port_line}

Current snapshot (ticker | signal | price | streak | period_return | confidence% | ADX | win_rate/expectancy):
{snapshot_block}

Signal effectiveness — avg next-trading-day % return across all historical data:
{fwd_line}"""


def build_prompt(all_data: A.AllData, today: str) -> str:
    data_sections = _build_data_sections(all_data, today)

    return f"""{data_sections}

Respond with ONLY this JSON object (no markdown fences, no text outside the JSON):
{{
  "generatedAt": "{today}",
  "marketSummary": "2-3 sentences on the overall signal environment — reference the BUY/SELL/HOLD split, whether the strategy is beating buy-and-hold, and any notable signal changes today",
  "topPicks": [{{"ticker": "TICK", "reason": "specific, data-backed reason in one sentence"}}],
  "riskWatch": [{{"ticker": "TICK", "reason": "specific, data-backed concern in one sentence"}}],
  "portfolioNote": "1-2 sentences on portfolio health, strategy vs buy-and-hold, or actionable guidance"
}}

Rules:
- topPicks: 1–3 tickers with the strongest BUY conviction (long BUY streak, high confidence, positive expectancy, strong ADX).
- riskWatch: 1–3 tickers on SELL signals, weak confidence, negative expectancy, or contradictions (BUY signal with negative expectancy, or SELL with positive expectancy — flag explicitly).
- Highlight tickers that just changed signal today as momentum shifts worth watching.
- Be specific: cite actual ticker names, streak lengths, confidence scores, or % figures.
- Do not invent data not present above."""
